# Generated by Django 5.2.5 on 2025-08-08 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_case_cpu_cpucooler_gpu_hddstorage_motherboard_psu_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ssdstorage',
            options={'verbose_name': 'SSD Storage', 'verbose_name_plural': 'SSD Storages'},
        ),
        migrations.AlterField(
            model_name='case',
            name='description',
            field=models.TextField(help_text='Detailed description of the component So that youser can see what it is in the frontend'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='description',
            field=models.TextField(help_text='Detailed description of the component So that youser can see what it is in the frontend'),
        ),
        migrations.AlterField(
            model_name='cpucooler',
            name='description',
            field=models.TextField(help_text='Detailed description of the component So that youser can see what it is in the frontend'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='description',
            field=models.TextField(help_text='Detailed description of the component So that youser can see what it is in the frontend'),
        ),
        migrations.AlterField(
            model_name='hddstorage',
            name='description',
            field=models.TextField(help_text='Detailed description of the component So that youser can see what it is in the frontend'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='description',
            field=models.TextField(help_text='Detailed description of the component So that youser can see what it is in the frontend'),
        ),
        migrations.AlterField(
            model_name='psu',
            name='description',
            field=models.TextField(help_text='Detailed description of the component So that youser can see what it is in the frontend'),
        ),
        migrations.AlterField(
            model_name='psu',
            name='power_rating',
            field=models.PositiveIntegerField(help_text='Power rating in Watts'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='description',
            field=models.TextField(help_text='Detailed description of the component So that youser can see what it is in the frontend'),
        ),
        migrations.AlterField(
            model_name='ssdstorage',
            name='description',
            field=models.TextField(help_text='Detailed description of the component So that youser can see what it is in the frontend'),
        ),
        migrations.CreateModel(
            name='PCBuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.case')),
                ('cpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cpu')),
                ('cpu_cooler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cpucooler')),
                ('gpu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.gpu')),
                ('hdd_storage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.hddstorage')),
                ('motherboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.motherboard')),
                ('psu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.psu')),
                ('ram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ram')),
                ('ssd_storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ssdstorage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pc_builds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PC Build',
                'verbose_name_plural': 'PC Builds',
                'ordering': ['-created_at'],
            },
        ),
    ]
